### ISSUE TITLE
Message size?

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/scuttlebot.io#20]
On this page:

https://scuttlebot.io/docs/message-types/post.html

When says each message must be 8KB or smaller, does it mean 8000 bytes or 8192 bytes (8KiB)?

(I just wanted some clarification before I try to implement https://github.com/arj03/ssb-browser-demo/issues/130)

**Comment by KyleMaas** [comment]
I think I found it.  Looks like it's actually 8KiB:

https://github.com/ssbc/ssb-db/pull/112/commits/5461395a539201e3029e8255833b11ba7926510d

I'm thinking it would be good if the documentation could be updated to reflect this.

**Comment by KyleMaas** [comment]
Another reference to 8192 bytes:

https://github.com/ssb-js/ssb-validate/blob/main/index.js#L110

**Comment by clehner** [comment]
@KyleMaas
That is where it is checked and it does say 8192 bytes - but it's really counting characters. A message can be larger than 8192 bytes if it uses multi-byte Unicode characters. This is discussed in this `git-ssb` issue thread: [`%fuIIizj5f83NqxMtu7MpBiRqMI7p8siclCX2wMg0ubM=.sha256`](https://git.scuttlebot.io/%25fuIIizj5f83NqxMtu7MpBiRqMI7p8siclCX2wMg0ubM%3D.sha256). How do you propose to update the docs?

**Comment by KyleMaas** [comment]
@clehner I guess I would say the docs should at least clarify that it's referring to characters, then.  Maybe change:

`There's not a limit on the length of the text, but all Scuttlebot messages (including their headers) must be less than 8KB.`

To something like:

`There's not a limit on the length of the text, but all Scuttlebot messages (including their headers) should be no longer than 8KiB (8192 bytes) for compatibility.  However, due to a quirk in validation of some legacy clients, messages up to 8192 UTF-8 characters must be tolerated.`

**Comment by clehner** [comment]
@KyleMaas That sounds good, except I'm not sure about `some legacy clients`. Message validation is a core functionality rather than a client functionality - although clients could add additional limits on what they publish and render. This is in the `ssb-server` stack which is still in active development. The Sunrise Choir (Rust) stack appears to use a different limit, 16385, [here](https://github.com/sunrise-choir/ssb-legacy-msg/blob/master/src/verify.rs#L73), calculated [here](https://github.com/sunrise-choir/legacy-msg-data/blob/master/src/lib.rs#L160) (This might be equivalent to the limit in the JS implementation, I'm not sure.) I couldn't find the relevant corresponding code for `go-sbot`. The Rust modules say "legacy message verification", but I think it is referring to all existing SSB as "legacy". The specification refers to the length calculation and limit (but not the specific length limit), [here](https://spec.scuttlebutt.nz/feed/datamodel.html#length-computation) and does not refer to it as legacy - actually it used to but that was changed, [here](https://github.com/sunrise-choir/spec/commit/82801311e9b76c907c4caec836966b50eb3f2432#diff-060eb42d26bb4202e0d35b41b8f6adc7678eef5d687fd363ed18e3b16f0fbc60R168).

**Comment by KyleMaas** [comment]
@clehner I was mostly going by this:

https://github.com/ssb-js/ssb-validate/blob/61e735696a79944a65046c25c1d46f3346f88b05/index.js#L107

Which is in the current version of ssb-validate.  I would assume from this that all clients which use a current version of ssb-validate allow for 8192 UTF-8 characters.  This looks (to the uneducated - me) to be because some clients went with a character length for validation when the original intent appears to be a byte length, so the only reason to limit yourself to 8192 characters instead of bytes is to support clients which implemented the original intent rather than the revised spec.  The point I was trying to get across is that it's probably a good idea to emit a maximum of 8192 bytes but are allowed to emit (and *must* accept) up to a hard stop maximum of 8192 UTF-8 characters.  But if you feel that needs to be said differently or can specify it more exactly, go ahead and change it.

Point of this whole thing is that "8KB" is both a little too vague (and apparently also wrong).  "8 kibicharacters" maybe, but not "8 kilobytes".  However you think it needs to be said will almost certainly be an improvement.  :)

**Comment by clehner** [comment]
@KyleMaas
Opened PR: #22
